# Generated by Django 2.1.1 on 2018-09-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='title',
            field=models.CharField(default='1', max_length=100, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='desc',
            field=models.TextField(max_length=50000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='book',
            name='desc',
            field=models.TextField(max_length=50000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Английский'), (1, 'Русский')], verbose_name='Язык'),
        ),
    ]
