# Generated by Django 2.1.1 on 2018-09-29 14:30

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20180929_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(2, 'На модерации'), (1, 'Опубликовано'), (3, 'Заблокированно')], default='1', verbose_name='Статус'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(2, 'На модерации'), (1, 'Опубликовано'), (3, 'Заблокированно')], default='1', verbose_name='Статус'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='desc',
            field=ckeditor.fields.RichTextField(max_length=50000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Русский'), (2, 'Английский')], verbose_name='Язык'),
        ),
    ]
