# Generated by Django 2.1.1 on 2018-09-30 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20180929_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='1', max_length=150, unique=True, verbose_name='Слак'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(2, 'На модерации'), (3, 'Заблокированно'), (1, 'Опубликовано')], verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(2, 'На модерации'), (3, 'Заблокированно'), (1, 'Опубликовано')], verbose_name='Статус'),
        ),
    ]
