# Generated by Django 2.1.1 on 2018-10-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20181005_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Опубликовано'), (2, 'На модерации'), (3, 'Заблокированно')], verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Опубликовано'), (2, 'На модерации'), (3, 'Заблокированно')], verbose_name='Статус'),
        ),
    ]
