# Generated by Django 2.1.1 on 2018-10-05 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20181005_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default='1', max_length=100, unique=True, verbose_name='ЧПУ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(max_length=150, unique=True, verbose_name='ЧПУ'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Заблокированно'), (2, 'На модерации'), (1, 'Опубликовано')], verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='articles', to='books.Tag', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Заблокированно'), (2, 'На модерации'), (1, 'Опубликовано')], verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='books', to='books.Tag', verbose_name='Теги'),
        ),
    ]
