# Generated by Django 2.1.1 on 2018-10-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20181005_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='slug',
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Английский'), (1, 'Русский')], verbose_name='Язык'),
        ),
    ]
