# Generated by Django 2.1.1 on 2018-10-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20181005_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default='', max_length=100, unique=True, verbose_name='ЧПУ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(2, 'На модерации'), (1, 'Опубликовано'), (3, 'Заблокированно')], verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(2, 'На модерации'), (1, 'Опубликовано'), (3, 'Заблокированно')], verbose_name='Статус'),
        ),
    ]
