# Generated by Django 2.1.1 on 2018-10-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_auto_20181005_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Опубликовано'), (3, 'Заблокированно'), (2, 'На модерации')], verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Английский'), (1, 'Русский')], verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Опубликовано'), (3, 'Заблокированно'), (2, 'На модерации')], verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='ЧПУ'),
        ),
    ]
