# Generated by Django 2.1.1 on 2018-10-05 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_auto_20181005_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Заблокированно'), (1, 'Опубликовано'), (2, 'На модерации')], verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Заблокированно'), (1, 'Опубликовано'), (2, 'На модерации')], verbose_name='Статус'),
        ),
    ]
