# Generated by Django 2.1.1 on 2018-11-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_auto_20181005_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Опубликовано'), (2, 'На модерации'), (3, 'Заблокированно')], verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Опубликовано'), (2, 'На модерации'), (3, 'Заблокированно')], default=2, verbose_name='Статус'),
        ),
    ]
